"""Thermoregulation system - processing load balance for Mae.

Biological basis: Hypothalamic thermoregulation. The hypothalamus monitors
core body temperature and activates heating (shivering, vasoconstriction)
or cooling (sweating, vasodilation) responses to maintain the optimal range
of 36.1-37.2 C. Too cold = enzyme dysfunction. Too hot = protein denaturation.

In Mae, "temperature" represents processing load balance:
- 0.0 = cold (completely idle, no useful work)
- 0.5 = optimal (balanced processing load)
- 1.0 = hot (overloaded, thrashing, degraded performance)

Optimal range: 0.3-0.7

Thermoregulatory responses:
| Condition      | Temp    | Response            | Biological Analog   |
|----------------|---------|---------------------|---------------------|
| Hypothermia    | < 0.2   | Force-activate idle | Shivering            |
| Cold           | < 0.3   | Encourage activity  | Vasoconstriction     |
| Optimal        | 0.3-0.7 | No action needed    | Normal               |
| Warm           | > 0.7   | Throttle activity   | Vasodilation         |
| Hyperthermia   | > 0.8   | Force-throttle busy | Sweating             |

Law compliance:
- Law 6: autopoietic closure - temperature drives corrections that adjust temperature
- Law 8 property (8): prediction/error-correction - feedback-driven regulation

EventBus channels:
- coordination.cooling_needed - throttle signal
- coordination.warming_needed - activate signal
- coordination.temperature_normal - stable signal
"""

from __future__ import annotations

import json
import logging
from typing import Any, Optional

from mae_core.backbone.event_bus import EventBus

logger = logging.getLogger(__name__)

# EventBus channels
CH_COOLING_NEEDED = "coordination.cooling_needed"
CH_WARMING_NEEDED = "coordination.warming_needed"
CH_TEMPERATURE_NORMAL = "coordination.temperature_normal"

# Temperature thresholds
TEMP_HYPOTHERMIA = 0.2
TEMP_COLD = 0.3
TEMP_WARM = 0.7
TEMP_HYPERTHERMIA = 0.8

# Default cooling/heating rates
NATURAL_COOLING_RATE = 0.02  # Temperature decays toward 0.5 naturally
SHIVER_HEAT = 0.05  # Heat generated by forced activation
SWEAT_COOL = 0.05  # Cooling from forced throttling


class ThermoregulationSystem:
    """Mae's thermoregulation - processing load balance maintenance.

    Tracks activity levels reported by individual systems, computes
    an aggregate "temperature", and generates heating/cooling signals
    to maintain optimal balance.
    """

    CH_COOLING_NEEDED = CH_COOLING_NEEDED
    CH_WARMING_NEEDED = CH_WARMING_NEEDED
    CH_TEMPERATURE_NORMAL = CH_TEMPERATURE_NORMAL

    def __init__(
        self,
        event_bus: Optional[EventBus] = None,
        optimal_low: float = TEMP_COLD,
        optimal_high: float = TEMP_WARM,
    ) -> None:
        self.event_bus = event_bus
        self._optimal_low = optimal_low
        self._optimal_high = optimal_high

        # Core state
        self._temperature: float = 0.5  # Starts at optimal center
        self._heat_sources: dict[str, float] = {}  # system_name -> activity_level (0-1)

        # Response tracking
        self._shivering: bool = False
        self._sweating: bool = False
        self._last_response: str = "normal"

        # History
        self._temperature_history: list[tuple[int, float]] = []
        self._max_history = 200
        self._step_count = 0

        # Throttle/activate lists (systems targeted by thermoregulation)
        self._throttled_systems: list[str] = []
        self._activated_systems: list[str] = []

        logger.info(
            "ThermoregulationSystem initialized (optimal=%.1f-%.1f)",
            self._optimal_low,
            self._optimal_high,
        )

    # =========================================================================
    # Activity Reporting
    # =========================================================================

    def report_activity(self, system_name: str, activity_level: float) -> None:
        """Called by systems to report their current activity level.

        Args:
            system_name: Name of the reporting system.
            activity_level: 0.0 (idle) to 1.0 (maximum load).
        """
        self._heat_sources[system_name] = max(0.0, min(1.0, activity_level))

    def remove_source(self, system_name: str) -> None:
        """Remove a system from heat tracking (e.g., when it shuts down)."""
        self._heat_sources.pop(system_name, None)

    # =========================================================================
    # Core Logic
    # =========================================================================

    def _compute_temperature(self) -> float:
        """Compute current temperature from system activity levels.

        Temperature is the weighted average of all active heat sources.
        If no sources are reporting, temperature decays toward 0.5.
        """
        if not self._heat_sources:
            # No sources: drift toward neutral
            return self._temperature + (0.5 - self._temperature) * NATURAL_COOLING_RATE

        total_activity = sum(self._heat_sources.values())
        count = len(self._heat_sources)

        # Weighted average biased toward high activity
        avg_activity = total_activity / count

        # Blend current temperature toward the computed target
        # (smooth transitions, not instant jumps)
        blend_rate = 0.3
        new_temp = self._temperature + (avg_activity - self._temperature) * blend_rate

        return max(0.0, min(1.0, new_temp))

    def _apply_natural_regulation(self, temp: float) -> float:
        """Apply natural drift toward optimal center (0.5).

        Like basal metabolic rate maintaining body temperature,
        the system naturally gravitates toward the midpoint.
        """
        drift = (0.5 - temp) * NATURAL_COOLING_RATE
        return max(0.0, min(1.0, temp + drift))

    def _handle_shivering(self) -> None:
        """Force-activate idle systems when temperature is critically low.

        Biological analog: involuntary muscle contractions (shivering)
        generate metabolic heat when core temperature drops dangerously.
        """
        self._shivering = True
        self._activated_systems.clear()

        # Find idle systems and mark them for activation
        for name, activity in self._heat_sources.items():
            if activity < 0.2:
                self._activated_systems.append(name)
                # Simulate forced activation by increasing their reported activity
                self._heat_sources[name] = min(1.0, activity + SHIVER_HEAT * 5)

        # Even without sources, add heat
        self._temperature = min(1.0, self._temperature + SHIVER_HEAT)

        logger.info(
            "Shivering: temp=%.2f, activated %d idle systems",
            self._temperature,
            len(self._activated_systems),
        )

    def _handle_sweating(self) -> None:
        """Force-throttle busiest systems when temperature is critically high.

        Biological analog: evaporative cooling (sweating) and vasodilation
        dissipate excess heat when core temperature rises dangerously.
        """
        self._sweating = True
        self._throttled_systems.clear()

        # Find busiest systems and throttle them
        sorted_sources = sorted(
            self._heat_sources.items(), key=lambda x: x[1], reverse=True
        )
        for name, activity in sorted_sources:
            if activity > 0.5:
                self._throttled_systems.append(name)
                self._heat_sources[name] = max(0.0, activity - SWEAT_COOL * 5)

        # Direct cooling
        self._temperature = max(0.0, self._temperature - SWEAT_COOL)

        logger.info(
            "Sweating: temp=%.2f, throttled %d busy systems",
            self._temperature,
            len(self._throttled_systems),
        )

    def step(self, current_step: int = 0) -> None:
        """Update temperature and generate regulation signals.

        1. Compute current temperature from heat sources
        2. Apply natural regulation (drift toward center)
        3. Check thresholds and generate responses
        4. Handle emergency shivering/sweating
        5. Publish appropriate EventBus signal
        """
        self._step_count = current_step if current_step > 0 else self._step_count + 1

        # Reset response state
        self._shivering = False
        self._sweating = False
        self._throttled_systems.clear()
        self._activated_systems.clear()

        # 1. Compute temperature from sources
        self._temperature = self._compute_temperature()

        # 2. Apply natural regulation
        self._temperature = self._apply_natural_regulation(self._temperature)

        # 3-4. Check thresholds and respond
        if self._temperature < TEMP_HYPOTHERMIA:
            # Emergency: critically cold
            self._handle_shivering()
            self._last_response = "shivering"
            if self.event_bus is not None:
                self.event_bus.publish(
                    CH_WARMING_NEEDED,
                    {
                        "temperature": round(self._temperature, 4),
                        "severity": "critical",
                        "activated_systems": list(self._activated_systems),
                        "step": self._step_count,
                    },
                )
        elif self._temperature < self._optimal_low:
            # Cold: encourage activity
            self._last_response = "warming"
            if self.event_bus is not None:
                self.event_bus.publish(
                    CH_WARMING_NEEDED,
                    {
                        "temperature": round(self._temperature, 4),
                        "severity": "mild",
                        "step": self._step_count,
                    },
                )
        elif self._temperature > TEMP_HYPERTHERMIA:
            # Emergency: critically hot
            self._handle_sweating()
            self._last_response = "sweating"
            if self.event_bus is not None:
                self.event_bus.publish(
                    CH_COOLING_NEEDED,
                    {
                        "temperature": round(self._temperature, 4),
                        "severity": "critical",
                        "throttled_systems": list(self._throttled_systems),
                        "step": self._step_count,
                    },
                )
        elif self._temperature > self._optimal_high:
            # Warm: throttle activity
            self._last_response = "cooling"
            if self.event_bus is not None:
                self.event_bus.publish(
                    CH_COOLING_NEEDED,
                    {
                        "temperature": round(self._temperature, 4),
                        "severity": "mild",
                        "step": self._step_count,
                    },
                )
        else:
            # Optimal: everything is fine
            self._last_response = "normal"
            if self.event_bus is not None:
                self.event_bus.publish(
                    CH_TEMPERATURE_NORMAL,
                    {
                        "temperature": round(self._temperature, 4),
                        "step": self._step_count,
                    },
                )

        # Record history
        self._temperature_history.append((self._step_count, round(self._temperature, 4)))
        if len(self._temperature_history) > self._max_history:
            self._temperature_history = self._temperature_history[-self._max_history:]

    # =========================================================================
    # Public Query API
    # =========================================================================

    @property
    def temperature(self) -> float:
        """Current temperature (0.0=cold to 1.0=hot)."""
        return self._temperature

    @property
    def is_optimal(self) -> bool:
        """Whether temperature is within optimal range."""
        return self._optimal_low <= self._temperature <= self._optimal_high

    @property
    def is_shivering(self) -> bool:
        """Whether shivering response is active."""
        return self._shivering

    @property
    def is_sweating(self) -> bool:
        """Whether sweating response is active."""
        return self._sweating

    def get_zone(self) -> str:
        """Return the current temperature zone name."""
        if self._temperature < TEMP_HYPOTHERMIA:
            return "hypothermia"
        elif self._temperature < self._optimal_low:
            return "cold"
        elif self._temperature > TEMP_HYPERTHERMIA:
            return "hyperthermia"
        elif self._temperature > self._optimal_high:
            return "warm"
        else:
            return "optimal"

    # =========================================================================
    # Observability
    # =========================================================================

    def get_statistics(self) -> dict[str, Any]:
        """Return thermoregulation statistics for monitoring."""
        return {
            "temperature": round(self._temperature, 4),
            "zone": self.get_zone(),
            "is_optimal": self.is_optimal,
            "is_shivering": self._shivering,
            "is_sweating": self._sweating,
            "last_response": self._last_response,
            "heat_source_count": len(self._heat_sources),
            "heat_sources": {k: round(v, 3) for k, v in self._heat_sources.items()},
            "throttled_systems": list(self._throttled_systems),
            "activated_systems": list(self._activated_systems),
            "optimal_range": [self._optimal_low, self._optimal_high],
            "history_length": len(self._temperature_history),
            "step_count": self._step_count,
        }

    # =========================================================================
    # Persistence (Tier 2)
    # =========================================================================

    def serialize(self) -> dict:
        """Serialize thermoregulation state for persistence."""
        return {
            "temperature": self._temperature,
            "heat_sources": dict(self._heat_sources),
            "last_response": self._last_response,
            "optimal_low": self._optimal_low,
            "optimal_high": self._optimal_high,
            "step_count": self._step_count,
        }

    def restore(self, data: dict) -> None:
        """Restore thermoregulation state from serialized data."""
        if not isinstance(data, dict):
            return

        self._temperature = float(data.get("temperature", 0.5))
        self._heat_sources = {
            str(k): float(v)
            for k, v in data.get("heat_sources", {}).items()
        }
        self._last_response = str(data.get("last_response", "normal"))
        self._optimal_low = float(data.get("optimal_low", self._optimal_low))
        self._optimal_high = float(data.get("optimal_high", self._optimal_high))
        self._step_count = int(data.get("step_count", 0))

    # =========================================================================
    # Internal Helpers
    # =========================================================================

    @staticmethod
    def _parse_message(message: Any) -> Optional[dict]:
        """Parse an EventBus message (may be JSON string or dict)."""
        if isinstance(message, dict):
            return message
        if isinstance(message, str):
            try:
                parsed = json.loads(message)
                if isinstance(parsed, dict):
                    return parsed
            except (json.JSONDecodeError, TypeError):
                pass
        return None
